import { StyleSheet } from 'react-native';
import { colors } from '../../constants/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F6F7F8',
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginTop: 10,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  menuButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22.5,
    width: 45,
    height: 45,
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuIcon: {
    width: 18,
    height: 14,
    backgroundColor: '#000',
    opacity: 0.7,
  },
  locationContainer: {
    flex: 1,
    paddingLeft: 18,
  },
  locationLabel: {
    color: '#3498db',
    fontWeight: 'bold',
    fontSize: 12,
  },
  locationWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    color: '#676767',
    fontSize: 14,
    marginTop: 5,
  },
  arrowDown: {
    width: 8,
    height: 5,
    backgroundColor: '#000',
    marginLeft: 8,
    marginTop: 5,
    opacity: 0.5,
  },
  profileImage: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#97A8B7',
  },
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  statsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    width: '47%',
    height: 115,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  statsNumber: {
    fontSize: 52,
    fontWeight: 'bold',
    color: '#32343E',
  },
  statsLabel: {
    fontSize: 13,
    color: '#838699',
    fontWeight: 'bold',
    marginTop: 5,
  },
  revenueCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 24,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 16,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 14,
    color: '#32343E',
  },
  revenueAmount: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#32343E',
    marginTop: 5,
  },
  headerRight: {
    alignItems: 'flex-end',
  },
  periodSelector: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.87,
    borderColor: '#E8E9EC',
    borderRadius: 7,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginBottom: 5,
  },
  periodText: {
    fontSize: 12,
    color: '#9B9BA5',
    marginRight: 5,
  },
  arrowDownSmall: {
    width: 6,
    height: 3,
    backgroundColor: '#9B9BA5',
  },
  seeDetails: {
    color: '#3498db',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  chartContainer: {
    height: 140,
    marginTop: 16,
  },
  chartPlaceholder: {
    flex: 1,
    backgroundColor: '#F9F9F9',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  tooltipBox: {
    position: 'absolute',
    backgroundColor: '#32343E',
    borderRadius: 5,
    paddingVertical: 6,
    paddingHorizontal: 17,
    top: 18,
    left: '25%',
  },
  tooltipText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  timeLabels: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  timeLabel: {
    fontSize: 9,
    color: '#9B9BA5',
  },
  reviewsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 24,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 16,
  },
  reviewStats: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
  },
  starIcon: {
    width: 26,
    height: 26,
    backgroundColor: '#3498db',
    borderRadius: 13,
    marginRight: 5,
  },
  ratingText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#3498db',
  },
  totalReviews: {
    fontSize: 14,
    color: '#32343E',
  },
  seeAll: {
    color: '#3498db',
    fontSize: 14,
    textDecorationLine: 'underline',
  },
  popularItemsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    marginHorizontal: 24,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginBottom: 80, // Extra bottom margin for tab bar
  },
  itemsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 15,
  },
  itemImage: {
    width: '48%',
    height: 153,
    backgroundColor: '#F0F0F0',
    borderRadius: 8,
  },
  tabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 89,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
    paddingBottom: 20, // For home indicator area on newer iPhones
  },
  bottomTabBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 85,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 10,
    paddingTop: 15,
    paddingBottom: 15,
  },
  tabItem: {
    width: 70,
    height: 65,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 8,
  },
  tabLabel: {
    fontSize: 12,
    marginTop: 5,
    textAlign: 'center',
  },
  gridIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#32343E',
    opacity: 0.5,
  },
  menuTabIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#32343E',
    opacity: 0.5,
  },
  addButton: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#E6F7FF',
    borderWidth: 1.5,
    borderColor: '#3498db',
    borderRadius: 24, 
    marginBottom: 5,
    position: 'relative',
    top: -15, 
  },
  plusIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#3498db',
    borderRadius: 12,
  },
  bellIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#32343E',
    opacity: 0.5,
  },
  userIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#32343E',
    opacity: 0.5,
  },
  welcomeContainer: {
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 16,
    backgroundColor: '#F8F8F8',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
  },
  welcomeText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
    marginBottom: 8,
  },
  statusText: {
    fontSize: 14,
    color: '#666',
  },
});